"""Create tables

Revision ID: a490856f700b
Revises:
Create Date: 2025-10-19 17:12:24.247885

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a490856f700b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "address",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("street_one", sa.String(length=50), nullable=False),
        sa.Column("street_two", sa.String(length=50), nullable=True),
        sa.Column("city", sa.String(length=50), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column("zip_code", sa.String(length=10), nullable=False),
        sa.Column("country", sa.String(length=3), nullable=False),
        sa.Column("hash", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.String(length=50), nullable=False),
        sa.Column("updated_by", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="party_service",
    )
    op.create_table(
        "party",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("middle_name", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("phone_number", sa.String(length=10), nullable=False),
        sa.Column("address_id", sa.Integer(), nullable=False),
        sa.Column("hash", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.String(length=50), nullable=False),
        sa.Column("updated_by", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["address_id"],
            ["party_service.address.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="party_service",
    )
    op.create_table(
        "party_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("party_id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("middle_name", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("phone_number", sa.String(length=10), nullable=False),
        sa.Column("street_one", sa.String(length=50), nullable=False),
        sa.Column("street_two", sa.String(length=50), nullable=True),
        sa.Column("city", sa.String(length=50), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column("zip_code", sa.String(length=10), nullable=False),
        sa.Column("country", sa.String(length=3), nullable=False),
        sa.Column("party_created_at", sa.DateTime(), nullable=False),
        sa.Column("party_updated_at", sa.DateTime(), nullable=False),
        sa.Column("party_created_by", sa.String(length=50), nullable=False),
        sa.Column("party_updated_by", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.String(length=50), nullable=False),
        sa.Column("updated_by", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["party_id"],
            ["party_service.party.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="party_service",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("party_history", schema="party_service")
    op.drop_table("party", schema="party_service")
    op.drop_table("address", schema="party_service")
    # ### end Alembic commands ###
